"""Added_Created_At_to_Friendship

Revision ID: da5b888b00ca
Revises: 00dbbfc9716c
Create Date: 2025-05-03 16:02:51.644681

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da5b888b00ca"
down_revision = "00dbbfc9716c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_friends", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_friends", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
