name: Lint Python Code

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - main

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install black pylint

    - name: Check formatting with black
      run: |
        black --check .

    - name: Lint Python code with pylint
      run: |
        pylint src/ --disable=C0114,C0415,R0903,R0401
